name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: flutter build apk --release

